#:schema node_modules/wrangler/config-schema.json
name = "template-dev"
compatibility_date = "2024-12-18"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "planet-bun"
database_id = "0c2592ef-c165-47cd-9586-48b329aedd87"

